Minor lib/*.sh include changes, add notify.sh, rewrite batt.
Change the include logic for library scripts to be slightly simpler for
the ctual source lines. Add a variable check to prevent lib being
sourced more than once.
Add 'lib/notify.sh' as a rewrite of 'lib/send_message.sh', keeping the
interface similar to 'lib/output.sh' with 'info' and 'error' functions,
etc. It uses 'notify-send' if XAUTHORITY, and 'echo's if connected to a
terminal or logging (LOG set). Add a compat layer for send_message
(including symlinking to notify.sh). Change 'sbin/wifi', etc. to use now
interface.
Rewrite 'bin/batt' so it should work with multiple batteries, only
source libraries when needed, and add in a '-n' option for
'notify-send'ing (for use with keyboard shortcuts).
BUGS:
    'colour.sh' seems to be broken

diff --git a/bin/batt b/bin/batt
--- a/bin/batt
+++ b/bin/batt
@@ -2,58 +2,84 @@
 # SCRIPTS_DIR/bin/batt
 
 [ -h "${0}" ] &&
-    script_path="$(/bin/readlink -f "${0}")" ||
-    script_path="${0}"
-. "${script_path%/*}/../lib/percent_blocks.sh"
-. "${script_path%/*}/../lib/colour.sh"
+    script_p="$(readlink -f "${0}")" ||
+    script_p="${0}"
+lib_d="${script_p%/*/*}/lib"
 
-location="/sys/class/power_supply/BAT1"
-current=$(cat ${location}/charge_now)
-full=$(cat ${location}/charge_full)
-design=$(cat ${location}/charge_full_design)
-percent=$(( (${current} * 1000 / ${full} + 5) / 10 ))
-life=$(( (${full} * 1000 / ${design} + 5) / 10 ))
+bat_loc="/sys/class/power_supply/BAT"
+for var in now full full_design
+do
+    for loc in ${bat_loc}*
+    do
+	read v < ${loc}/charge_${var}
+	eval "${var}=\"\${${var}} + ${v}\""
+    done
+    eval "${var}=\"(\${${var}# + })\""
+done
+percent=$(( (${now} * 1000 / ${full} + 5) / 10 ))
+life=$(( (${full} * 1000 / ${full_design} + 5) / 10 ))
 
+usage="Usage: ${0} [-c FG] [-k BG] [-w WIDTH] [-v|-f|-l|-b|-n]"
 while true
 do
     case "${1}" in
 	'')
 	    echo "${percent} %"
 	    ;;
-	-v)
-	    echo "${current} / ${full} = ${percent} %"
+	'-v')
+	    echo "${now} / ${full} = ${percent} %"
 	    ;;
-	-f)
-	    echo "current: ${current}; full: ${full}; design: ${design}; %: ${percent}."
+	'-l')
+	    echo "life: ${full} / ${full_design} = ${life} %"
 	    ;;
-	-l)
-	    echo "life: ${full} / ${design} = ${life} %"
+	'-f')
+	    #echo "current ${now}; full ${full}; design ${full_design}; %: ${percent}"
+	    echo "current: ${now} / ${full}	= ${percent} %"
+	    echo "life:    ${full} / ${full_design}	= ${life} %"
 	    ;;
-	-b)
-	    echo -n ${fmt}
+	'-b')
+	    . "${lib_d}/percent_blocks.sh"
 	    [ ${width-1} -gt 1 ] &&
 		pc_hblock ${percent} ${width} ||
 		pc_vblock ${percent}
 	    ;;
-	-w*)
-	    [ -z "${1#-w}" ] && shift
+	'-n')
+	    . "${lib_d}/notify.sh"
+	    case ${percent} in
+		[0-9])	icon=gpm-battery-000;;
+		[1-2]?)	icon=gpm-battery-020;;
+		[3-4]?)	icon=gpm-battery-040;;
+		[5-6]?)	icon=gpm-battery-060;;
+		[7-8]?)	icon=gpm-battery-080;;
+		9?|100)	icon=gpm-battery-100;;
+	    esac
+	    show "Battery:" "${percent} %"
+	    ;;
+	'-w'*)
+	    [ "${1}" = '-w' ] && shift
 	    width="${1#-w}"
-	    shift; continue
+	    shift && continue
 	    ;;
-	-c*)
-	    [ -z "${1#-c}" ] && shift
+	'-c'*)
+	    . "${lib_d}/colour.sh"
+	    [ "${1}" = '-c' ] && shift
 	    set_fg_colour "${1#-c}"
-	    shift; continue
+	    echo -n "${fmt}"
+	    shift && continue
 	    ;;
-	-k*)
-	    [ -z "${1#-k}" ] && shift
+	'-k'*)
+	    . "${lib_d}/colour.sh"
+	    [ "${1}" = '-k' ] && shift
 	    set_bg_colour "${1#-k}"
-	    shift; continue
+	    echo -n "${fmt}"
+	    shift && continue
+	    ;;
+	'-h'|'-?')
+	    echo "${usage}" >&2
 	    ;;
 	*)
-	    [ -n "${*}" ] &&
-		echo "Invalid: ${*}" >&2
-	    echo "Usage: ${0} [ -v | -f | -l | -b ]" >&2
+	    echo "Invalid: ${*}" >&2
+	    echo "${usage}" >&2
 	    exit 1
 	    ;;
     esac
diff --git a/sbin/wifi b/sbin/wifi
--- a/sbin/wifi
+++ b/sbin/wifi
@@ -10,10 +10,11 @@ log="${LOG-/dev/null}"
 
 ## souce library scripts	{{{1
 [ -h "${0}" ] &&
-    script_path="$(readlink -f "${0}")" ||
-    script_path="${0}"
-. "${script_path%/*}/../lib/send_message.sh"
-. "${script_path%/*}/../lib/prog.sh"
+    script_p="$(readlink -f "${0}")" ||
+    script_p="${0}"
+lib_d="${script_p%/*/*}/lib"
+. "${lib_d}/notify.sh"
+. "${lib_d}/prog.sh"
 
 ## Global Variables	{{{1
 
@@ -102,14 +103,14 @@ wifi_stop () {
 		dae=true mod=true
 		;;
 	    *)
-		send_message -w "Wifi Stop" "Invalid option: '${1}'"
+		warn "Wifi Stop" "Invalid option: '${1}'"
 		;;
 	esac
 	shift
     done
     # check its not already stopped
     ${force} || wifi_status || {
-	send_message -w "Wifi already stopped."
+	warn "Wifi already stopped."
 	return 2
     }
     # stop active connections
@@ -119,28 +120,28 @@ wifi_stop () {
 	${_rfkill} block wifi >"${log}" 2>&1
 	init_rf		# check
 	echo "${rf_list}" | sed -ne "/[Ss]oft [Bb]locked.* no/q1" && {
-	    send_message -i "Wifi Stop -" "soft blocked Wifi"
+	    info "Wifi Stop -" "soft blocked Wifi"
 	} || {
-	    send_message -e "Wifi Stop Failed -" "could not soft block Wifi."
+	    error "Wifi Stop Failed -" "could not soft block Wifi."
 	    ${dae} || ${mod} || return 1
 	}
     } 
     { ${dae} || ! ${rf_control}; } && {
 	# If we don't have rf control first stop daemon
 	${wifi_initscript} stop >"${log}" 2>&1 &&
-	    send_message -i "Wifi Stop -" "${_wifi##*/} daemon stopped" ||
-	    send_message -e "Wifi Stop -" "${_wifi##*/} failed to stop" ||
+	    info "Wifi Stop -" "${_wifi##*/} daemon stopped" ||
+	    error "Wifi Stop -" "${_wifi##*/} failed to stop" ||
 	# Check wicd has actually stopped
 	local wifi_pid
 	wifi_pid="$(${_pgrep} -x "${_wifi##*/}" 2>"${log}")" && {
 	    sleep "${timeout}"
 	    [ -d "/proc/${wifi_pid}" ] && {
-		send_message -w "Wifi Stop -" "Trying to kill ${_wifi##*/}..."
+		warn "Wifi Stop -" "Trying to kill ${_wifi##*/}..."
 		kill "${wifi_pid}" >"${log}" 2>&1
 		sleep "${timeout}"
 		[ -d "/proc/${wifi_pid}" ] &&
-		    send_message -e "Kill ${_wifi##*/}" "Failed." ||
-		    send_message -i "Kill ${_wifi##*/}" "Succeded."
+		    error "Kill ${_wifi##*/}" "Failed." ||
+		    info "Kill ${_wifi##*/}" "Succeded."
 	    }
 	}
     }
@@ -154,18 +155,18 @@ wifi_stop () {
 	done
 	# check
 	sed -ne "/${wifi_mod_regex}/q1" </proc/modules && {
-	    send_message -i "Wifi Stop -" "modulues removed"
+	    info "Wifi Stop -" "modulues removed"
 	} || {
-	    send_message -e "Wifi Stop Failed -" "modules could not be removed."
+	    error "Wifi Stop Failed -" "modules could not be removed."
 	    return 1
 	}
     }
-    send_message "Wifi Stopped."
+    show "Wifi Stopped."
 }
 
 wifi_start () {
     ${force} || ! wifi_status || {
-	send_message -w "Wifi already started."
+	warn "Wifi already started."
 	return 2
     }
     ${rf_control} && {
@@ -173,9 +174,9 @@ wifi_start () {
 	${_rfkill} unblock wifi >"${log}" 2>&1
 	init_rf		# check
 	echo "${rf_list}" | sed -ne "/[Ss]oft [Bb]locked.* yes/q1" && {
-	    send_message -i "Wifi unblocked."
+	    info "Wifi unblocked."
 	} || {
-	    send_message -e "Wifi Start Failed -" "could not unblock Wifi."
+	    error "Wifi Start Failed -" "could not unblock Wifi."
 	    return 1
 	}
     }
@@ -204,8 +205,7 @@ wifi_start () {
 	    die "Wifi Start Failed -" "no available modules"
 	local wifi_mod=${starting_wifi_mods%% *}
 	[ ${mods_count} -gt 1 ] &&
-	    send_message -w "Multiple modules available," \
-		"loading the first: ${wifi_mod}"
+	    warn "Multiple modules available," "loading the first: ${wifi_mod}"
 	# concaternate modules_${wireless_mod}_${release} arguments
 	local release="${RELEASE}"
 	local mod_args=""
@@ -221,16 +221,16 @@ wifi_start () {
     # check if wicd daemon is running
     ${_pgrep} -x "${_wifi##*/}" >"${log}" 2>&1 ||
 	${wifi_initscript} start >"${log}" 2>&1 &&
-	    send_message -i "${_wifi##*/} Started..." ||
+	    info "${_wifi##*/} Started..." ||
 	    die "Wifi Start Failed -" "${_wifi##*/} could not start"
     # check if wicd client is running
     [ -n "${XAUTHORITY}" ] && {
 	${_pgrep} -x ${wifi_client##*/} >"${log}" 2>&1 ||
 	    sudo -bu ${USER} ${wifi_client-true} >"${log}" 2>&1
 	${_pgrep} -x ${wifi_client##*/} >"${log}" 2>&1 ||
-	    send_message -w "${wifi_client##*/} did not start"
+	    warn "${wifi_client##*/} did not start"
     }
-    send_message "Wifi Started"
+    show "Wifi Started"
 }
 
 ## Process Arguments and Execute	{{{1
@@ -240,7 +240,7 @@ while [ 1 -gt 0 ]
 do
     case "${1}" in
 	"toggle")
-	    send_message -i "Toggling Wifi..."
+	    info "Toggling Wifi..."
 	    shift
 	    if wifi_status
 	    then
@@ -250,17 +250,17 @@ do
 	    fi
 	    ;;
 	"start")
-	    send_message -i "Starting Wifi..."
+	    info "Starting Wifi..."
 	    shift
 	    wifi_start "${@}"
 	    ;;
 	"stop")
-	    send_message -i "Stopping Wifi..."
+	    info "Stopping Wifi..."
 	    shift
 	    wifi_stop "${@}"
 	    ;;
 	"restart")
-	    send_message -i "Restarting Wifi..."
+	    info "Restarting Wifi..."
 	    shift
 	    wifi_stop "${@}"
 	    sleep ${timeout}
@@ -268,8 +268,8 @@ do
 	    ;;
 	"status")
 	    wifi_status &&
-		send_message "Wifi Started" ||
-		send_message "Wifi Stopped"
+		show "Wifi Started" ||
+		show "Wifi Stopped"
 	    ;;
 	"-v"|"--verbose")
 	    verbose=true
